#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define MYPROJECT_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define MYPROJECT_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define MYPROJECT_VERSION_PATCH @PROJECT_VERSION_PATCH@

#define MYPROJECT_VERSION STR(MYPROJECT_VERSION_MAJOR) "." STR(MYPROJECT_VERSION_MINOR) "." STR(MYPROJECT_VERSION_PATCH)
